version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    restart: always
    env_file:
      - .env
    ports:
      - "4001:4000"
    # volumes:
    #   - ../file_bucket:/usr/src/file_bucket:rw
